### ISSUE TITLE
FEATURE REQUEST : Position of the Search Icon

### ISSUE THREAD

**Issue by wer-mathurin** [Dev-hwang/outline_search_bar#1]
The ability to position the search icon when visible.  Leading or trailing.

**Comment by Dev-hwang** [comment]
> The ability to position the search icon when visible. Leading or trailing.

The package has been updated. You can set the position of the search icon as shown below.

```dart
OutlineSearchBar(
  searchButtonPosition: SearchButtonPosition.leading,
  onSearchButtonPressed: (String keyword) {

  },
),
```
