### ISSUE TITLE
FEATURE REQUEST - add autocorrect flag

### ISSUE THREAD

**Issue by azeek** [Dev-hwang/outline_search_bar#3]
add autocorrect, enableSuggestions,  flag 

https://api.flutter.dev/flutter/material/TextField/autocorrect.html

https://api.flutter.dev/flutter/material/TextField/enableSuggestions.html

**Comment by Dev-hwang** [comment]
The autocorrect option is already available. Try using the plugin's auotCorrect option. The enableSuggestions option is always set to true, but I'll add it if necessary.
